version: '3'
volumes:
  rails:
networks: 
  db_redis:
  db_postgres:
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    networks: 
      - db_postgres
  redis:
    image: redis
    networks: 
      - db_redis
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/navedex_api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      db_redis:
      db_postgres:

